name: 运行错误
description: 有些东西的工作方式与预期不符？在这里报告。
labels: [bug]
body:
  - type: input
    id: bug-description
    attributes:
      label: 描述
      placeholder: 描述错误或问题
    validations:
      required: true
  - type: textarea
    id: bug-details
    attributes:
      label: 附加详情/重现步骤
    validations:
      required: true
  - type: textarea
    id: bug-support-info
    attributes:
      label: 发布版本号
      placeholder: "你用的是最新版，对吧？"
    validations:
      required: true
  - type: textarea
    id: bug-attachments
    attributes:
      label: 日志和截图
  - type: markdown
    attributes:
      value: |
        ## 感谢您的报告！
