name: 功能建议
description: 提出改进或新增功能的想法
title: "[功能建议] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 你希望添加的功能或改进是什么？
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 为什么需要这个功能？
      description: 说明该功能能解决什么问题或带来什么好处
